### ISSUE TITLE
Checking out as branch step may not be needed

### ISSUE THREAD

**Issue by cjfullerton** [hpcflow/python-release-workflow#1]
The step:
"Checkout this repo as a new branch in your repo: git checkout -b python-release-workflow/main python-release-workflow/main"
may not be necessary.

Using git (command line, macOS) I found that including this step caused the following warning:

 'warning refname 'python-release-workflow/main python-release-workflow/main' is ambiguous'

I'm assuming ambiguity is between branch you created and upstream repo?

I tried without the checkout as branch step, everything worked and there was no warning.

Suggest removing this step from instructions, unless needed in other environments (i.e. not using command line git).

**Comment by aplowman** [comment]
Is the fetch step still correct then: `git fetch python-release-workflow main:python-release-workflow/main`? If I omit the checkout and still do the fetch, the same local branch is created anyway, and I get the warning again. Should we just do `git fetch`?

**Comment by cjfullerton** [comment]
I'll have to check that - I followed the initial setup with `git fetch --all` which doesn't seem to have created any local branches.

I'll make some test commits and see if I can sync them to my local hpcflow repo without generating warnings.

**Comment by cjfullerton** [comment]
I've done some fiddling.

The required command is `git fetch python-release-workflow`.

This fetches all branches from `python-release-workflow` and automatically stores them in local branches `python-release-workflow/BRANCHNAME`. This means the branch step is surplus to requirements.

Then:
`git checkout python-release-workflow/BRANCHNAME -- .github/`

I'd suggest re-using `git fetch python-release-workflow` for future syncs rather than syncing specific branches.

I'll make a branch and amend README with new instructions
