### ISSUE TITLE
Fix poetry issue

### ISSUE THREAD

**Issue by cjfullerton** [hpcflow/python-release-workflow#21]
Poetry version fixed for most of actions apart from documentation building.

Docs sections uses latest Poetry version, but is currently failing.

Adding line:

`poetry config installer.modern-installation false`

repairs problem.

Consider using latest poetry version for all steps and including this line.

**Comment by cjfullerton** [comment]
For context, Poetry now uses a 'modern installation' method by default and no longer relies on pip: https://python-poetry.org/blog/announcing-poetry-1.4.0/

Suggested fix for failures is to turn off this method using option given in issue description. Better to understand why modern installation method is failing for us in the long term.

**Comment by cjfullerton** [comment]
Solution for now:

- [ ] Don't constrain poetry version
- [ ] Turn off modern installation method

**Comment by aplowman** [comment]
Or maybe constrain Poetry to a recent version, but every now and then upgrade manually, so we can check it all works? If we don't constrain it at all, then we end up in this situation, where they make a change which breaks our build process.

**Comment by cjfullerton** [comment]
Agreed - better to be in control of upgrades.

**Comment by cjfullerton** [comment]
Have tested this in build-exes and test workflows - it works everywhere apart from the build-executables-linux section. The docker container looks like it has poetry already installed and doesn't have pip installed, so we can't update to v1.4.

@aplowman Does this sound right to you?
