### ISSUE TITLE
GH actions workflow succeeding without running mocking tests

### ISSUE THREAD

**Issue by aplowman** [hpcflow/python-release-workflow#22]
In this build-exe run: https://github.com/hpcflow/hpcflow-new/actions/runs/4531211710/jobs/7981089857, the test suite cannot load the `mocker` fixture, so some tests don't run. But the workflow succeeds. Can we make the workflow fail in this case?

**Comment by cjfullerton** [comment]
Presumably because tests are running inside the pyinstaller app, gha just keeps going? Good check for exit codes from app and use these to cause workflow to fail.

**Comment by aplowman** [comment]
This might be fixed by [e7d214d ](https://github.com/hpcflow/hpcflow-new/commit/e7d214dbe551ae375203853edcbcc71dbad9dbf9)

**Comment by aplowman** [comment]
Yep, fixed. This fails as it should: https://github.com/hpcflow/hpcflow-new/actions/runs/4575918467
