### ISSUE TITLE
Fix deprecation warnings for our use of set-output in GHAs

### ISSUE THREAD

**Issue by aplowman** [hpcflow/python-release-workflow#36]
E.g. https://github.com/hpcflow/matflow-new/actions/runs/5033938296

**Comment by aplowman** [comment]
Looks like there is still one leftover in matflow: https://github.com/hpcflow/matflow-new/actions/runs/5406858390

**Comment by fherreazcue** [comment]
Sorry, forgot to update workflows in matflow... [this PR](https://github.com/hpcflow/matflow-new/pull/64) should fix it.
