### ISSUE TITLE
Remove spec file, build directory upload from Release workflow

### ISSUE THREAD

**Issue by cjfullerton** [hpcflow/python-release-workflow#4]
Used for debugging, but by release we anticipate debugging will be done.

**Comment by cjfullerton** [comment]
@aplowman - I'm going to remove these uploads from the release workflow, but I just realised that I'll probably end up adding the build directory back in when I start working on the install script.

The intention is to use the build directory for that, right?

**Comment by aplowman** [comment]
I don't think we'll use the `build` directory for that. I think we'll need to run pyinstaller twice (once with `--onefile`, and once with `--onedir` -- for use by the install script). In both cases, they add the final output to the `dist` directory.

**Comment by cjfullerton** [comment]
I got the wrong end of the stick then - build dir is used during the actual build process, but we can get a (cleaner, more user friendly) directory out of build.
