### ISSUE TITLE
Support Python 3.11 (in test matrix, and use for Pyinstaller builds)

### ISSUE THREAD

**Issue by aplowman** [hpcflow/python-release-workflow#9]
Will need to compile Python 3.11 in the CentOS image and re-build the image.

Will also need to update downstream `pyproject.toml` files.

**Comment by aplowman** [comment]
@aplowman to build new docker image; @cjfullerton to update GHA workflows.

**Comment by cjfullerton** [comment]
@aplowman , @fherreazcue - where are we on this? Unresolved issue with git on the CentOS image?

**Comment by cjfullerton** [comment]
Tests need updating, but docker image ready to go.
